# 1. Тест

sql.AnalysisTest.ADD = INSERT INTO public.tests(test_name, biomaterial, \
  execution_time_hours, price, unit) \
  VALUES (?, ?, ?, ?, ?);

sql.AnalysisTest.FIND_BY_ID = SELECT id_test, test_name, biomaterial, \
  execution_time_hours, price, unit FROM public.tests \
  WHERE id_test = ?;

sql.AnalysisTest.GET_ALL = SELECT id_test, test_name, biomaterial, \
  execution_time_hours, price, unit FROM public.tests;

sql.AnalysisTest.UPDATE = UPDATE public.tests SET test_name=?, biomaterial=?, \
  execution_time_hours=?, price=?, unit=? \
  WHERE id_test = ?;

sql.AnalysisTest.DELETE_BY_ID = DELETE FROM public.tests WHERE id_test = ?;

sql.AnalysisTest.FIND_BY_MATERIAL = SELECT id_test, test_name, biomaterial, \
  execution_time_hours, price, unit \
  FROM public.tests WHERE biomaterial =?;

sql.SEARCH_BY_NAME = SELECT id_test, test_name, biomaterial, \
  execution_time_hours, price, unit \
  FROM public.tests WHERE test_name ILIKE ?;



# 2. Сотрудник

sql.Employee.ADD = INSERT INTO public.employees(role, \"position\", \
  last_name, first_name, middle_name, login, password_hash) \
  VALUES (?, ?, ?, ?, ?, ?, ?);

sql.Employee.FIND_BY_ID = SELECT id_employee, role, \"position\", \
  last_name, first_name, middle_name, login, password_hash \
  FROM public.employees WHERE id_employee = ?;

sql.Employee.GET_ALL = SELECT id_employee, role, \"position\", \
  last_name, first_name, middle_name, login, password_hash \
  FROM public.employees;

sql.Employee.UPDATE = UPDATE public.employees SET role=?, \"position\"=?, \
  last_name=?, first_name=?, middle_name=?, login=?, password_hash=? \
  WHERE id_employee = ?;

sql.Employee.DELETE_BY_ID = DELETE FROM public.employees WHERE id_employee = ?;

sql.Employee.FIND_BY_LOGIN = SELECT id_employee, role, \"position\", \
  last_name, first_name, middle_name, login, password_hash \
  FROM public.employees WHERE login = ?;

sql.Employee.FIND_BY_ROLE = SELECT id_employee, role, \"position\", \
  last_name, first_name, middle_name, login, password_hash \
  FROM public.employees WHERE login = ?;

sql.Employee.SEARCH_BY_FULLNAME = SELECT id_employee, role, \"position\", \
  last_name, first_name, middle_name, login, password_hash \
  FROM public.employees \
  WHERE CONCAT_WS(' ', last_name, first_name, middle_name) ILIKE ?;


# 3. Заказ

sql.Order.ADD = INSERT INTO public.orders(status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, \
  verification_datetime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);

sql.Order.FIND_BY_ID = SELECT id_order, status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, \
  verification_datetime FROM public.orders WHERE id_order = ?;

sql.Order.GET_ALL = SELECT id_order, status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, \
  verification_datetime FROM public.orders;

sql.Order.UPDATE = UPDATE public.orders SET status_id=?, patient_id=?, organization_id=?, \
  registered_by=?, accepted_by=?, verified_by=?, registration_datetime=?, acceptance_datetime=?, \
  verification_datetime=? WHERE id_order = ?;

sql.Order.DELETE_BY_ID = DELETE FROM public.orders WHERE id_order = ?;

sql.Order.FIND_BY_PATIENT_ID = SELECT id_order, status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, \
  verification_datetime FROM public.orders WHERE patient_id = ?;

sql.Order.FIND_BY_STATUS_ID = SELECT id_order, status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, \
  verification_datetime FROM public.orders WHERE status_id = ?;

sql.Order.FIND_BY_DATE_RANGE = SELECT id_order, status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, verification_datetime \
  FROM public.orders \
  WHERE registration_datetime >= ? AND registration_datetime <= ? \
  ORDER BY registration_datetime DESC;

sql.Order.FIND_BY_REGISTERED_BY = SELECT id_order, status_id, patient_id, organization_id, \
  registered_by, accepted_by, verified_by, registration_datetime, acceptance_datetime, verification_datetime \
  FROM public.orders WHERE registered_by = ?;

sql.Order.FIND_BY_SPECIMEN_BARCODE = SELECT o.id_order, o.status_id, o.patient_id, o.organization_id, \
  o.registered_by, o.accepted_by, o.verified_by, o.registration_datetime, o.acceptance_datetime, \
  o.verification_datetime \
  FROM public.orders o \
  JOIN public.specimens s ON o.id_order = s.order_id \
  WHERE s.barcode = ?;

sql.Order.UPDATE_STATUS = UPDATE public.orders SET status_id = ? WHERE id_order = ?;


# 4. Позиция заказа

sql.OrderItem.ADD = INSERT INTO public.order_items(order_id, test_id, specimen_id, status, \
  result_value, result_text, is_abnormal, entered_by, entry_datetime) \
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);

sql.OrderItem.FIND_BY_ID = SELECT id_item, order_id, test_id, specimen_id, status, \
  result_value, result_text, is_abnormal, entered_by, entry_datetime \
  FROM public.order_items WHERE id_item = ?;

sql.OrderItem.GET_ALL = SELECT id_item, order_id, test_id, specimen_id, status, \
  result_value, result_text, is_abnormal, entered_by, entry_datetime \
  FROM public.order_items;

sql.OrderItem.UPDATE = UPDATE public.order_items SET order_id=?, test_id=?, specimen_id=?, \
  status=?, result_value=?, result_text=?, is_abnormal=?, entered_by=?, entry_datetime=? \
  WHERE id_item = ?;

sql.OrderItem.DELETE = DELETE FROM public.order_items WHERE id_item = ?;

sql.OrderItem.FIND_BY_ORDER_ID = SELECT id_item, order_id, test_id, specimen_id, status, \
  result_value, result_text, is_abnormal, entered_by, entry_datetime \
  FROM public.order_items WHERE order_id = ?;

sql.OrderItem.FIND_BY_SPECIMEN_ID = SELECT id_item, order_id, test_id, specimen_id, status, \
  result_value, result_text, is_abnormal, entered_by, entry_datetime \
  FROM public.order_items WHERE specimen_id = ?;

sql.OrderItem.FIND_BY_ENTERED_BY = SELECT id_item, order_id, test_id, specimen_id, status, \
  result_value, result_text, is_abnormal, entered_by, entry_datetime \
  FROM public.order_items WHERE entered_by = ?;

sql.OrderItem.UPDATE_RESULT = UPDATE public.order_items SET result_value = ?, result_text = ?, \
  is_abnormal = ?, entered_by = ?, entry_datetime = ?, status = '????????' WHERE id_item = ?;

sql.OrderItem.UPDATE_STATUS = UPDATE public.order_items SET status = ? WHERE id_item = ?;


# 5. Пациент

sql.Patient.ADD = INSERT INTO public.patients(policy_number, last_name, \
  first_name, middle_name, gender, birth_date, phone) \
  VALUES (?, ?, ?, ?, ?, ?, ?);

sql.Patient.FIND_BY_ID = SELECT id_patient, policy_number, last_name, first_name, \
  middle_name, gender, birth_date, phone \
  FROM public.patients WHERE id_patient = ?;

sql.Patient.GET_ALL = SELECT id_patient, policy_number, last_name, first_name, \
  middle_name, gender, birth_date, phone \
  FROM public.patients;

sql.Patient.UPDATE = UPDATE public.patients SET policy_number=?, last_name=?, \
  first_name=?, middle_name=?, gender=?, birth_date=?, phone=? \
  WHERE id_patient = ?;

sql.Patient.DELETE_BY_ID = DELETE FROM public.patients WHERE id_patient = ?;

sql.Patient.FIND_BY_POLICY = SELECT id_patient, policy_number, last_name, \
  first_name, middle_name, gender, birth_date, phone \
  FROM public.patients WHERE policy_number = ?;

sql.Patient.SEARCH_BY_FULLNAME = SELECT id_patient, policy_number, last_name, \
  first_name, middle_name, gender, birth_date, phone \
  FROM public.patients \
  WHERE CONCAT_WS(' ', last_name, first_name, middle_name) ILIKE ?;


# 6. Референсное значение

sql.ReferenceValue.ADD = INSERT INTO public.reference_values(test_id, gender_applicable, \
  age_min, age_max, ref_value_min, \
  ref_value_max, ref_text) \
  VALUES (?, ?, ?, ?, ?, ?, ?);

sql.ReferenceValue.GET_BY_ID = SELECT id_reference, test_id, gender_applicable, \
  age_min, age_max, ref_value_min, ref_value_max, ref_text \
  FROM public.reference_values WHERE id_reference = ?;

sql.ReferenceValue.GET_ALL = SELECT id_reference, test_id, gender_applicable, \
  age_min, age_max, ref_value_min, ref_value_max, ref_text \
  FROM public.reference_values;

sql.ReferenceValue.UPDATE = UPDATE public.reference_values SET test_id=?, gender_applicable=?, \
  age_min=?, age_max=?, ref_value_min=?, ref_value_max=?, ref_text=? \
  WHERE id_reference = ?;

sql.ReferenceValue.DELETE = DELETE FROM public.reference_values WHERE id_reference = ?;

sql.ReferenceValue.FIND_BY_TEST_ID = SELECT id_reference, test_id, gender_applicable, \
  age_min, age_max, ref_value_min, ref_value_max, ref_text \
  FROM public.reference_values WHERE test_id = ?;

sql.ReferenceValue.FIND_BY_TEST_AND_GENDER_AND_AGE = SELECT id_reference, test_id, gender_applicable, \
  age_min, age_max, ref_value_min, ref_value_max, ref_text \
  FROM public.reference_values \
  WHERE test_id = ? \
  AND gender_applicable = ? \
  AND (age_min IS NULL OR age_min <= ?) \
  AND (age_max IS NULL OR age_max >= ?);


# 7. Статус заказа

sql.OrderStatus.ADD = INSERT INTO public.order_statuses(status_name) VALUES (?);

sql.OrderStatus.FIND_BY_ID = SELECT id_status, status_name FROM public.order_statuses \
  WHERE id_status = ?;

sql.OrderStatus.GET_ALL = SELECT id_status, status_name FROM public.order_statuses;

sql.OrderStatus.DELETE_BY_ID = DELETE FROM public.order_statuses WHERE id_status = ?;

sql.OrderStatus.UPDATE = UPDATE public.order_statuses SET status_name=? WHERE id_status = ?;



# 8. Биологическая проба

sql.Specimen.ADD = INSERT INTO public.specimens(order_id, specimen_type, container_type, \
  collection_datetime, barcode) \
  VALUES (?, ?, ?, ?, ?);

sql.Specimen.FIND_BY_ID = SELECT id_specimen, order_id, specimen_type, container_type, \
  collection_datetime, barcode FROM public.specimens \
  WHERE id_specimen = ?;

sql.Specimen.GET_ALL = SELECT id_specimen, order_id, specimen_type, container_type, \
  collection_datetime, barcode FROM public.specimens;

sql.Specimen.UPDATE = UPDATE public.specimens SET order_id=?, specimen_type=?, \
  container_type=?, collection_datetime=?, barcode=? \
  WHERE id_specimen = ?;

sql.Specimen.DELETE = DELETE FROM public.specimens WHERE id_specimen = ?;

sql.Specimen.FIND_BY_BARCODE = SELECT id_specimen, order_id, specimen_type, container_type, \
  collection_datetime, barcode FROM public.specimens \
  WHERE barcode = ?;

sql.Specimen.FIND_BY_ORDER_ID = SELECT id_specimen, order_id, specimen_type, container_type, \
  collection_datetime, barcode FROM public.specimens \
  WHERE order_id = ?;


# 9. Организация

sql.Organization.ADD = INSERT INTO public.organizations(org_name, contract_number, contact_last_name, \
  contact_first_name, contact_middle_name, contact_person_phone) \
  VALUES (?, ?, ?, ?, ?, ?);

sql.Organization.FIND_BY_ID = SELECT id_org, org_name, contract_number, contact_last_name, \
  contact_first_name, contact_middle_name, contact_person_phone \
  FROM public.organizations WHERE id_org = ?;


sql.Organization.GET_ALL = SELECT id_org, org_name, contract_number, contact_last_name, \
  contact_first_name, contact_middle_name, contact_person_phone \
  FROM public.organizations;

sql.Organization.UPDATE = UPDATE public.organizations SET org_name=?, contract_number=?, \
  contact_last_name=?, contact_first_name=?, contact_middle_name=?, \
  contact_person_phone=? WHERE id_org = ?;

sql.Organization.DELETE_BY_ID = DELETE FROM public.organizations WHERE id_org = ?;

sql.Organization.SEARCH_BY_NAME = SELECT id_org, org_name, contract_number, contact_last_name, \
  contact_first_name, contact_middle_name, contact_person_phone \
  FROM public.organizations WHERE org_name ILIKE ?;

# 10. Отчёт и форма отчёта

sql.Report.GET_TEST_COUNT_BY_TYPE = SELECT t.test_name, COUNT(oi.id_item) AS cnt \
  FROM public.order_items oi \
  JOIN public.tests t ON oi.test_id = t.id_test \
  JOIN public.orders o ON oi.order_id = o.id_order \
  WHERE o.registration_datetime >= ? AND o.registration_datetime <= ? \
  AND oi.status = 'выполнен' \
  GROUP BY t.test_name ORDER BY cnt DESC

sql.Report.GET_WORKLOAD_BY_EMPLOYEE = SELECT e.last_name || ' ' || e.first_name || ' ' || e.middle_name AS fullname, \
  COUNT(oi.id_item) AS cnt \
  FROM public.order_items oi \
  JOIN public.employees e ON oi.entered_by = e.id_employee \
  JOIN public.orders o ON oi.order_id = o.id_order \
  WHERE o.registration_datetime >= ? AND o.registration_datetime <= ? \
  AND oi.status = 'выполнен' \
  GROUP BY fullname ORDER BY cnt DESC

sql.Report.GET_REVENUE_BY_ORGANIZATION = SELECT org.org_name, SUM(t.price) AS total_revenue \
  FROM public.order_items oi \
  JOIN public.tests t ON oi.test_id = t.id_test \
  JOIN public.orders o ON oi.order_id = o.id_order \
  JOIN public.organizations org ON o.organization_id = org.id_org \
  WHERE o.registration_datetime >= ? AND o.registration_datetime <= ? \
  AND oi.status = 'выполнен' \
  GROUP BY org.org_name ORDER BY total_revenue DESC

# 11. Аутентификация