@startuml
top to bottom direction
skinparam linetype ortho
skinparam nodesep 40
skinparam ranksep 30
skinparam defaultFontSize 20
skinparam classAttributeIconSize 0

' ========== ЛЕВАЯ КОЛОНКА ==========


' ========== ПРАВАЯ КОЛОНКА ==========
package "ru.kafpin124.rkpp_kursr" {


    package "dao & impl" {
        interface OrderDao
        interface OrderItemDao
        interface EmployeeDao
        interface PatientDao
        interface AnalysisTestDao
        interface ReferenceValueDao
        interface SpecimenDao
        interface OrganizationDao
        interface OrderStatusDao
        interface ReportDao

        package "impl" {
            class OrderDaoImpl
            class OrderItemDaoImpl
            class EmployeeDaoImpl
            class PatientDaoImpl
            class AnalysisTestDaoImpl
            class ReferenceValueDaoImpl
            class SpecimenDaoImpl
            class OrganizationDaoImpl
            class OrderStatusDaoImpl
            class ReportDaoImpl
        }
    }

    package "controller" {
        class LoginController
        class MainTabController
        class NewOrderController
        class NewResultController
        class OrdersListController
        class VerificationController
        class ManageEmployeesController
        class ManageTestsController
        class ReportsController
        class SelectPersonController
        class SelectTestController
        class ReportFormController
    }

    package "model" {
        class Employee
        class Patient
        class Order
        class OrderItem
        class AnalysisTest
        class ReferenceValue
        class Specimen
        class Organization
        class OrderStatus
    }

    package "dto" {
        class TestCountByType
        class EmployeeStatistic
        class OrganizationStatistic
    }

    package "utils" {
        class DBHelper
        class LocalizationService
        class SqlStatements
        class ScaleManager
    }

   class MainApplication
   class Launcher
}

' ========== ВЕРТИКАЛЬНОЕ ВЫРАВНИВАНИЕ В ЛЕВОЙ КОЛОНКЕ ==========
OrderDao -[hidden]down- OrderItemDao
OrderItemDao -[hidden]down- EmployeeDao
EmployeeDao -[hidden]down- PatientDao
PatientDao -[hidden]down- AnalysisTestDao
AnalysisTestDao -[hidden]down- ReferenceValueDao
ReferenceValueDao -[hidden]down- SpecimenDao
SpecimenDao -[hidden]down- OrganizationDao
OrganizationDao -[hidden]down- OrderStatusDao
OrderStatusDao -[hidden]down- ReportDao

OrderDaoImpl -[hidden]down- OrderItemDaoImpl
OrderItemDaoImpl -[hidden]down- EmployeeDaoImpl
EmployeeDaoImpl -[hidden]down- PatientDaoImpl
PatientDaoImpl -[hidden]down- AnalysisTestDaoImpl
AnalysisTestDaoImpl -[hidden]down- ReferenceValueDaoImpl
ReferenceValueDaoImpl -[hidden]down- SpecimenDaoImpl
SpecimenDaoImpl -[hidden]down- OrganizationDaoImpl
OrganizationDaoImpl -[hidden]down- OrderStatusDaoImpl
OrderStatusDaoImpl -[hidden]down- ReportDaoImpl

' ========== ВЕРТИКАЛЬНОЕ ВЫРАВНИВАНИЕ В ПРАВОЙ КОЛОНКЕ ==========
LoginController -[hidden]down- MainTabController
MainTabController -[hidden]down- NewOrderController
NewOrderController -[hidden]down- NewResultController
NewResultController -[hidden]down- OrdersListController
OrdersListController -[hidden]down- VerificationController
VerificationController -[hidden]down- ManageEmployeesController
ManageEmployeesController -[hidden]down- ManageTestsController
ManageTestsController -[hidden]down- ReportsController
ReportsController -[hidden]down- SelectPersonController
SelectPersonController -[hidden]down- SelectTestController
SelectTestController -[hidden]down- ReportFormController

Employee -[hidden]down- Patient
Patient -[hidden]down- Order
Order -[hidden]down- OrderItem
OrderItem -[hidden]down- AnalysisTest
AnalysisTest -[hidden]down- ReferenceValue
ReferenceValue -[hidden]down- Specimen
Specimen -[hidden]down- Organization
Organization -[hidden]down- OrderStatus

DBHelper -[hidden]down- LocalizationService
LocalizationService -[hidden]down- SqlStatements
SqlStatements -[hidden]down- ScaleManager
ScaleManager -[hidden]down- MainApplication
MainApplication -[hidden]right- Launcher

TestCountByType -[hidden]down- EmployeeStatistic
EmployeeStatistic -[hidden]down- OrganizationStatistic

' ========== ГОРИЗОНТАЛЬНАЯ СВЯЗЬ МЕЖДУ КОЛОНКАМИ ==========
OrderDao -[hidden]right- LoginController
OrderDaoImpl -[hidden]right- Employee

' ========== РЕАЛЬНЫЕ СВЯЗИ ==========
OrderDao <|.. OrderDaoImpl
OrderItemDao <|.. OrderItemDaoImpl
EmployeeDao <|.. EmployeeDaoImpl
PatientDao <|.. PatientDaoImpl
AnalysisTestDao <|.. AnalysisTestDaoImpl
ReferenceValueDao <|.. ReferenceValueDaoImpl
SpecimenDao <|.. SpecimenDaoImpl
OrganizationDao <|.. OrganizationDaoImpl
OrderStatusDao <|.. OrderStatusDaoImpl
ReportDao <|.. ReportDaoImpl

javafx.application.Application <|--up MainApplication

@enduml